Fixed big bug
Art-em1s/autogit pull request #1
Opened 2023-05-05 05:11 UTC by easton36

![hello](https://user-images.githubusercontent.com/105407282/236381665-b3d1947b-9d92-4d53-94a1-7c107cba603d.gif)

2023-05-05 05:25 UTC, Officialstrike requested changes
Not written in Rust, please rewrite in rust immediately!

2023-05-05 07:59 UTC, Art-em1s requested changes
Submit as a new file and I'll approve this

2023-05-06 19:50 UTC, Art-em1s approved these changes

2023-05-06 19:50 UTC, Art-em1s commented
Merging, I have some changes planned to handle edge cases & to introduce concurrency.

2023-05-06 19:50 UTC, merged